-- Panda Restaurant — Ordering system schema
-- Run after 001_create_menu_schema.sql. Safe to re-run.

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------------
-- restaurant_tables
-- ---------------------------------------------------------------------------
create table if not exists public.restaurant_tables (
  id           uuid primary key default gen_random_uuid(),
  table_number text not null,
  qr_slug      text not null unique,
  is_active    boolean not null default true,
  created_at   timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- restaurant_settings (single row)
-- ---------------------------------------------------------------------------
create table if not exists public.restaurant_settings (
  id                     uuid primary key default gen_random_uuid(),
  bank_name              text default 'Bank of Maldives',
  bank_account_name      text default 'Panda Restaurant Pvt Ltd',
  bank_account_number    text default '7730000123456',
  payment_instructions   text default 'Transfer the total amount and upload your payment slip.',
  cash_enabled           boolean not null default true,
  bank_transfer_enabled  boolean not null default true,
  online_payment_enabled boolean not null default false,
  delivery_enabled       boolean not null default true,
  takeaway_enabled       boolean not null default true,
  dine_in_enabled        boolean not null default true,
  service_charge_percent numeric not null default 10,
  tax_percent            numeric not null default 8,
  delivery_fee_mvr       numeric not null default 30,
  minimum_order_mvr      numeric not null default 75,
  delivery_area_note     text default 'We deliver across Himandhoo Island only.',
  estimated_prep_time    text default '20–30 min',
  estimated_delivery_time text default '30–45 min',
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- orders
-- ---------------------------------------------------------------------------
create table if not exists public.orders (
  id                   uuid primary key default gen_random_uuid(),
  order_number         bigint generated by default as identity,
  order_type           text not null,
  table_id             uuid references public.restaurant_tables (id),
  table_number         text,
  customer_name        text,
  customer_phone       text,
  delivery_address     text,
  delivery_landmark    text,
  delivery_notes       text,
  pickup_time          text,
  status               text not null default 'new',
  payment_status       text not null default 'unpaid',
  payment_method       text,
  subtotal_mvr         numeric not null default 0,
  service_charge_mvr   numeric not null default 0,
  delivery_fee_mvr     numeric not null default 0,
  tax_mvr              numeric not null default 0,
  total_mvr            numeric not null default 0,
  notes                text,
  source               text not null default 'website',
  estimated_ready_time text,
  slip_image_url       text,
  new_order_telegram_sent boolean not null default false,
  confirmed_order_telegram_sent boolean not null default false,
  last_notification_sent_at timestamptz,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- order_items (snapshot of menu item name + price at order time)
-- ---------------------------------------------------------------------------
create table if not exists public.order_items (
  id             uuid primary key default gen_random_uuid(),
  order_id       uuid not null references public.orders (id) on delete cascade,
  menu_item_id   uuid references public.menu_items (id),
  item_name      text not null,
  item_price_mvr numeric not null,
  quantity       integer not null default 1,
  item_notes     text,
  line_total_mvr numeric not null,
  created_at     timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- payments
-- ---------------------------------------------------------------------------
create table if not exists public.payments (
  id                    uuid primary key default gen_random_uuid(),
  order_id              uuid not null references public.orders (id) on delete cascade,
  payment_method        text,
  payment_status        text not null default 'unpaid',
  amount_mvr            numeric,
  slip_image_url        text,
  transaction_reference text,
  admin_note            text,
  paid_at               timestamptz,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

create index if not exists orders_status_idx on public.orders (status);
create index if not exists orders_created_idx on public.orders (created_at desc);

alter table public.orders add column if not exists new_order_telegram_sent boolean not null default false;
alter table public.orders add column if not exists confirmed_order_telegram_sent boolean not null default false;
alter table public.orders add column if not exists last_notification_sent_at timestamptz;
create index if not exists order_items_order_idx on public.order_items (order_id);

-- ---------------------------------------------------------------------------
-- Seed defaults
-- ---------------------------------------------------------------------------
insert into public.restaurant_settings (id)
select gen_random_uuid()
where not exists (select 1 from public.restaurant_settings);

insert into public.restaurant_tables (table_number, qr_slug, is_active)
select g::text, 'table-' || g, true
from generate_series(1, 8) g
on conflict (qr_slug) do nothing;

-- ---------------------------------------------------------------------------
-- Row Level Security
--   Public: can create orders + order_items, read tables/settings.
--   Authenticated admin: full control.
-- ---------------------------------------------------------------------------
alter table public.restaurant_tables enable row level security;
alter table public.restaurant_settings enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.payments enable row level security;

drop policy if exists "public read tables" on public.restaurant_tables;
create policy "public read tables" on public.restaurant_tables for select using (true);
drop policy if exists "admin manage tables" on public.restaurant_tables;
create policy "admin manage tables" on public.restaurant_tables for all to authenticated using (true) with check (true);

drop policy if exists "public read settings" on public.restaurant_settings;
create policy "public read settings" on public.restaurant_settings for select using (true);
drop policy if exists "admin manage settings" on public.restaurant_settings;
create policy "admin manage settings" on public.restaurant_settings for all to authenticated using (true) with check (true);

drop policy if exists "public create orders" on public.orders;
create policy "public create orders" on public.orders for insert with check (true);
drop policy if exists "public read orders" on public.orders;
create policy "public read orders" on public.orders for select using (true);
drop policy if exists "admin update orders" on public.orders;
create policy "admin update orders" on public.orders for update to authenticated using (true) with check (true);

drop policy if exists "public create order items" on public.order_items;
create policy "public create order items" on public.order_items for insert with check (true);
drop policy if exists "public read order items" on public.order_items;
create policy "public read order items" on public.order_items for select using (true);

drop policy if exists "public create payments" on public.payments;
create policy "public create payments" on public.payments for insert with check (true);
drop policy if exists "admin manage payments" on public.payments;
create policy "admin manage payments" on public.payments for all to authenticated using (true) with check (true);
